name: 3D Contribution Calendar

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          TIME_ZONE: Europe/Moscow
      - name: Commit
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git diff --cached --quiet || git commit -m "chore: update 3D contribution calendar"
          git pull --rebase
          git push
